### ISSUE TITLE
Nametag Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [DerDevHD/TeamChat#1]
When my Supporter write in Teamchat, he has the Name of another Player
Sorry for my Englisch
Teamchat Latest
Pocketmine Latest

**Comment by DerDevHD** [comment]
Do you use a Nickname Plugin? Its caused because in the Format of the Team Chat shows only the real name of the player, and not the displayname.

**Comment by Killian92** [comment]
Yes i use NickUI
But no one has used a Nickname.
Example: Supporter A write Hey
His Name is another Playername from Team

**Comment by DerDevHD** [comment]
Ahh, my code has a little Error. I fix it as soon as possible.
